name: jr_case_boilerplate
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.0+1
  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  envied: ^1.1.1
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  google_fonts: ^6.3.1
  riverpod_annotation: ^2.6.1
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  jwt_decoder: ^2.0.1
  hooks_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^10.2.3
  analyzer: ^7.4.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  hardcoded_strings_lint: ^1.0.1
  slang_build_runner: ^4.7.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  min_sdk_android: 21
  image_path: "assets/images/IconImage.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/IconImage.png"

flutter:
  uses-material-design: true
  assets:
    - assets/anims/
    - assets/icons/
    - assets/images/
